### ISSUE TITLE
Elephant and SubIssue buttons aren't rendered anymore

### ISSUE THREAD

**Issue by francescogior** [buildo/github-workflow-pal#93] opened 2016-08-29 14:28 UTC
## description
- probably caused by https://github.com/buildo/github-workflow-pal/pull/92

## how to reproduce
- {optional: describe steps to reproduce defect}

**Comment by FrancescoCioria** [comment] 2016-08-29 14:45
duplicate of #94

**Closed by FrancescoCioria** 2016-08-29 14:45 UTC
Labels: defect
